server:
  port: 8001
spring:
  application:
    name: order-service
eureka:
  client:
    service-url:
        defaultZone: http://peer1:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
